### ISSUE TITLE
Can I build and run tensorflow 1.8.0 on the Hikey960？

### ISSUE THREAD

**Issue by luckzhiwei** [codeplaysoftware/tensorflow#19]
### Describe the problem
Hi,I have read your article from this link----[
TensorFlow™ ARM Setup Guide](https://developer.codeplay.com/computecppce/latest/tensorflow-arm-setup-guide),I see your build tensorflow steps are these:

- git clone http://github.com/codeplaysoftware/tensorflow
- cd tensorflow
- git checkout 1ca6b1d

The first problem is : I want to know the “1ca6b1d” corresponding version is ? tensorflow 1.6.0?   
The second problem is: I want to build tensorflow 1.8.0 on Hikey 960, Can I follow the above steps that is described in your article and let tensorflow 1.8.0 successsfully  support GPU on Hikey 960?  
Thank you very much!

**Comment by Rbiessy** [comment]
Hello,
The TensorFlow version of a specific commit can be found in the RELEASE.md file, in this case it is TensorFlow 1.6.0.
We don't have a commit for 1.8.0 but we do have 1.9.0. You should be able to use this with minor changes to the instructions:
- use the latest commit of the eigen_sycl branch (https://github.com/codeplaysoftware/tensorflow/commit/290d731683e0abb0392ff6aa48e55417e446f0f0)
- use the latest version of ComputeCpp (1.0.2)
- use bazel 0.16.0

Make sure the commands use versions that match the above.
Hope this helps, let us know if you have any issue!

**Comment by luckzhiwei** [comment]
t helps me a lot.I will follow your valuable advice to try it. Thank.you. 
If I still have  problems,I will open issue again

**Comment by foromer4** [comment]
I am trying to go over the tutorial with the suggested changes, I get this error:
... protobut/stubs/common.h:38:10: fatal error: 'algoirthm' file is not found

**Comment by Rbiessy** [comment]
Hello,
There could be an issue with your toolchain. I'm assuming you're using an ARM 64bit architecture, are you using the toolchain `gcc-linaro-6.3.1-2017.05-x86_64_aarch64-linux-gnu` like in the instructions? If so can you verify that the `algorithm` file is present with:
```
find gcc-linaro-6.3.1-2017.05-x86_64_aarch64-linux-gnu -type f -name "algorithm"
```
You should get:
```
gcc-linaro-6.3.1-2017.05-x86_64_aarch64-linux-gnu/aarch64-linux-gnu/include/c++/6.3.1/algorithm
gcc-linaro-6.3.1-2017.05-x86_64_aarch64-linux-gnu/aarch64-linux-gnu/include/c++/6.3.1/parallel/algorithm
gcc-linaro-6.3.1-2017.05-x86_64_aarch64-linux-gnu/aarch64-linux-gnu/include/c++/6.3.1/ext/algorithm
gcc-linaro-6.3.1-2017.05-x86_64_aarch64-linux-gnu/aarch64-linux-gnu/include/c++/6.3.1/experimental/algorithm
```
If that doesn't help can you paste us the full command line?

**Comment by foromer4** [comment]
@Rbiessy  , Thanks I downloaded again the toolchain and it passed that part. However i'm now failing to builld , something to do with python. (I am trying to build against a manually downloaded version of python 3.6). I think it might be an issue of the PYTHON_LIB_PATH , I tried poinitng it to:
```
/usr/local/lib/python3.6/site-packages
/usr/local/include/python36.m
/home/armnn/devel/git/tensorflow/venv/lib/python3.6/site-packages
```
And I get various exceptions of missing h files. (assert, string, etc...)
Here is an example:

```
/home/armnn/devel/git/tensorflow/tensorflow/core/kernels/BUILD:3444:1: C++ compilation of rule '//tensorflow/core/kernels:nth_element_op' failed (Exit 1): compute failed: error executing command 
  (cd /home/armnn/tensorflow_temp/84fe3d6a011d8dbbf1f9dc8b8352b468/execroot/org_tensorflow && \
  exec env - \
    COMPUTECPP_TOOLKIT_PATH=/home/armnn/devel/ComputeCpp-CE-1.0.2-Ubuntu-16.04-ARM_64 \
    LD_LIBRARY_PATH=/home/armnn/armnn-devenv/google/x86_64_pb_install/lib/: \
    PATH=/home/armnn/devel/git/tensorflow/venv/bin:/home/armnn/armnn-devenv/google/x86_64_pb_install/bin/:/home/armnn/bin:/home/armnn/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/local/bin/python3.6 \
    PYTHON_LIB_PATH=/usr/local/lib/python3.6/site-packages \
    TF_DOWNLOAD_CLANG=0 \
    TF_NEED_COMPUTECPP=1 \
    TF_NEED_CUDA=0 \
    TF_NEED_OPENCL_SYCL=1 \
    TF_SYCL_BITCODE_TARGET=spirv64 \
  /home/armnn/devel/ComputeCpp-CE-1.0.2-Ubuntu-16.04-ARM_64/bin/compute -target aarch64-linux-gnu '--gcc-toolchain=/home/armnn/gcc-linaro-6.3.1-2017.05-x86_64_aarch64-linux-gnu' '--sysroot=/home/armnn/gcc-linaro-6.3.1-2017.05-x86_64_aarch64-linux-gnu/aarch64-linux-gnu/libc' -ffunction-sections -fdata-sections -fPIC -fno-omit-frame-pointer -Wall -g0 -O2 -DNDEBUG '-std=c++11' -fsycl-ih-last -mllvm '-inline-threshold=10000' -sycl-driver -cl-denorms-are-zero -cl-fp32-correctly-rounded-divide-sqrt -cl-mad-enable '-fsycl-split-modules=20' -sycl-target spirv64 '-DTENSORFLOW_USE_SYCL=1' '-DEIGEN_USE_SYCL=1' '-DEIGEN_HAS_C99_MATH=1' '-DEIGEN_HAS_CXX11_MATH=1' -Wno-unused-variable -Wno-unused-const-variable -MD -MF bazel-out/armeabi-opt/bin/tensorflow/core/kernels/_objs/nth_element_op/nth_element_op.pic.d '-frandom-seed=bazel-out/armeabi-opt/bin/tensorflow/core/kernels/_objs/nth_element_op/nth_element_op.pic.o' -fPIC -DEIGEN_MPL2_ONLY '-DEIGEN_MAX_ALIGN_BYTES=64' -D__CLANG_SUPPORT_DYN_ANNOTATION__ -DTENSORFLOW_USE_ABSL -DTF_USE_SNAPPY -iquote . -iquote bazel-out/armeabi-opt/genfiles -iquote bazel-out/armeabi-opt/bin -iquote external/nsync -iquote bazel-out/armeabi-opt/genfiles/external/nsync -iquote bazel-out/armeabi-opt/bin/external/nsync -iquote external/bazel_tools -iquote bazel-out/armeabi-opt/genfiles/external/bazel_tools -iquote bazel-out/armeabi-opt/bin/external/bazel_tools -iquote external/eigen_archive -iquote bazel-out/armeabi-opt/genfiles/external/eigen_archive -iquote bazel-out/armeabi-opt/bin/external/eigen_archive -iquote external/local_config_sycl -iquote bazel-out/armeabi-opt/genfiles/external/local_config_sycl -iquote bazel-out/armeabi-opt/bin/external/local_config_sycl -iquote external/opencl_headers -iquote bazel-out/armeabi-opt/genfiles/external/opencl_headers -iquote bazel-out/armeabi-opt/bin/external/opencl_headers -iquote external/com_google_absl -iquote bazel-out/armeabi-opt/genfiles/external/com_google_absl -iquote bazel-out/armeabi-opt/bin/external/com_google_absl -iquote external/gif_archive -iquote bazel-out/armeabi-opt/genfiles/external/gif_archive -iquote bazel-out/armeabi-opt/bin/external/gif_archive -iquote external/jpeg -iquote bazel-out/armeabi-opt/genfiles/external/jpeg -iquote bazel-out/armeabi-opt/bin/external/jpeg -iquote external/protobuf_archive -iquote bazel-out/armeabi-opt/genfiles/external/protobuf_archive -iquote bazel-out/armeabi-opt/bin/external/protobuf_archive -iquote external/com_googlesource_code_re2 -iquote bazel-out/armeabi-opt/genfiles/external/com_googlesource_code_re2 -iquote bazel-out/armeabi-opt/bin/external/com_googlesource_code_re2 -iquote external/farmhash_archive -iquote bazel-out/armeabi-opt/genfiles/external/farmhash_archive -iquote bazel-out/armeabi-opt/bin/external/farmhash_archive -iquote external/fft2d -iquote bazel-out/armeabi-opt/genfiles/external/fft2d -iquote bazel-out/armeabi-opt/bin/external/fft2d -iquote external/highwayhash -iquote bazel-out/armeabi-opt/genfiles/external/highwayhash -iquote bazel-out/armeabi-opt/bin/external/highwayhash -iquote external/png_archive -iquote bazel-out/armeabi-opt/genfiles/external/png_archive -iquote bazel-out/armeabi-opt/bin/external/png_archive -iquote external/zlib_archive -iquote bazel-out/armeabi-opt/genfiles/external/zlib_archive -iquote bazel-out/armeabi-opt/bin/external/zlib_archive -iquote external/double_conversion -iquote bazel-out/armeabi-opt/genfiles/external/double_conversion -iquote bazel-out/armeabi-opt/bin/external/double_conversion -iquote external/local_config_cuda -iquote bazel-out/armeabi-opt/genfiles/external/local_config_cuda -iquote bazel-out/armeabi-opt/bin/external/local_config_cuda -Ibazel-out/armeabi-opt/bin/external/opencl_headers/_virtual_includes/OpenCL-Headers -isystem external/nsync/public -isystem bazel-out/armeabi-opt/genfiles/external/nsync/public -isystem bazel-out/armeabi-opt/bin/external/nsync/public -isystem external/eigen_archive -isystem bazel-out/armeabi-opt/genfiles/external/eigen_archive -isystem bazel-out/armeabi-opt/bin/external/eigen_archive -isystem external/local_config_sycl/sycl -isystem bazel-out/armeabi-opt/genfiles/external/local_config_sycl/sycl -isystem bazel-out/armeabi-opt/bin/external/local_config_sycl/sycl -isystem external/local_config_sycl/sycl/include -isystem bazel-out/armeabi-opt/genfiles/external/local_config_sycl/sycl/include -isystem bazel-out/armeabi-opt/bin/external/local_config_sycl/sycl/include -isystem external/gif_archive/lib -isystem bazel-out/armeabi-opt/genfiles/external/gif_archive/lib -isystem bazel-out/armeabi-opt/bin/external/gif_archive/lib -isystem external/protobuf_archive/src -isystem bazel-out/armeabi-opt/genfiles/external/protobuf_archive/src -isystem bazel-out/armeabi-opt/bin/external/protobuf_archive/src -isystem external/farmhash_archive/src -isystem bazel-out/armeabi-opt/genfiles/external/farmhash_archive/src -isystem bazel-out/armeabi-opt/bin/external/farmhash_archive/src -isystem external/png_archive -isystem bazel-out/armeabi-opt/genfiles/external/png_archive -isystem bazel-out/armeabi-opt/bin/external/png_archive -isystem external/zlib_archive -isystem bazel-out/armeabi-opt/genfiles/external/zlib_archive -isystem bazel-out/armeabi-opt/bin/external/zlib_archive -isystem external/double_conversion -isystem bazel-out/armeabi-opt/genfiles/external/double_conversion -isystem bazel-out/armeabi-opt/bin/external/double_conversion -isystem external/local_config_cuda/cuda -isystem bazel-out/armeabi-opt/genfiles/external/local_config_cuda/cuda -isystem bazel-out/armeabi-opt/bin/external/local_config_cuda/cuda -isystem external/local_config_cuda/cuda/cuda/include -isystem bazel-out/armeabi-opt/genfiles/external/local_config_cuda/cuda/cuda/include -isystem bazel-out/armeabi-opt/bin/external/local_config_cuda/cuda/cuda/include -isystem external/local_config_cuda/cuda/cuda/include/crt -isystem bazel-out/armeabi-opt/genfiles/external/local_config_cuda/cuda/cuda/include/crt -isystem bazel-out/armeabi-opt/bin/external/local_config_cuda/cuda/cuda/include/crt '-DUSE_DEFAULT_SELECTOR=1' -DARM_NON_MOBILE -DNO_LOCAL_MEM -DEIGEN_DONT_VECTORIZE_SYCL -Wno-c++11-narrowing '-DTENSORFLOW_SYCL_NO_HALF=1' '-DTENSORFLOW_SYCL_NO_DOUBLE=1' '-DTENSORFLOW_SYCL_NO_HALF=1' '-DTENSORFLOW_SYCL_NO_DOUBLE=1' -DEIGEN_AVOID_STL_ARRAY -Iexternal/gemmlowp -Wno-sign-compare '-ftemplate-depth=900' -pthread -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -no-canonical-prefixes -c tensorflow/core/kernels/nth_element_op.cc -o bazel-out/armeabi-opt/bin/tensorflow/core/kernels/_objs/nth_element_op/nth_element_op.pic.o)
In file included from tensorflow/core/kernels/nth_element_op.cc:17:
In file included from ./tensorflow/core/kernels/nth_element_op.h:19:
./tensorflow/core/framework/op_kernel.h:19:10: fatal error: 'functional' file not found
#include <functional>
         ^~~~~~~~~~~~
1 error generated.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 1115.566s, Critical Path: 41.90s
INFO: 1023 processes: 1023 local.
FAILED: Build did NOT complete successfully

```

**Comment by Rbiessy** [comment]
That's interesting it's not the first time that I see the download of this tarball failing, maybe we should add a sha256sum check.
This error you posted is very similar to the previous one (i.e. a system header is missing). So again, this file should be found in the downloaded toolchain. Can you find it?
You can also run this command to make sure the tarball you downloaded is correct:
```
sha256sum gcc-linaro-6.3.1-2017.05-x86_64_aarch64-linux-gnu.tar.xz | grep 26b45fdfb1656f94fa2b5117494f5d338b619c1f453ee3f3e1d84d79e90f2403
```
I never tried to build with python 3.6. There could be a few small failures but it shouldn't be a big issue.

**Comment by foromer4** [comment]
Oh , I see what's wrong here. in the script the gcc is not copied in full, see:
https://developer.codeplay.com/computecppce/latest/tensorflow-arm-setup-guide
...
tar -xf gcc-linaro-6.3.1-2017.05-x86_64_aarch64-linux-gnu.tar.xz
mkdir -p $HOME/gcc-linaro-6.3.1-2017.05-x86_64_aarch64-linux-gnu/aarch64-linux-gnu/libc/usr/include/aarch64-linux-gnu
So it is assumed it was downloaded to home folder, and I missed it. thanks
